package com.swifta.sub.mats.operation.provisioning.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1 2014-11-12T01:02:26.180+03:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", name = "Provisioning")
@XmlSeeAlso({ com.swifta.sub.mats.operation.provisioning.v1.ObjectFactory.class })
public interface Provisioning {

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "resetpassword", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Resetpassword")
	@WebMethod(action = "resetpassword")
	@ResponseWrapper(localName = "resetpasswordResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.ResetpasswordResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse resetpassword(
			@WebParam(name = "forcepasswordchangeafterlogin", targetNamespace = "") java.lang.Boolean forcepasswordchangeafterlogin);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addpermissionstoaccountprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addpermissionstoaccountprofile")
	@WebMethod(action = "addpermissionstoaccountprofile")
	@ResponseWrapper(localName = "addpermissionstoaccountprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddpermissionstoaccountprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addpermissionstoaccountprofile(
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile,
			@WebParam(name = "activepermissions", targetNamespace = "") java.util.List<java.lang.String> activepermissions);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addbackofusers", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addbackofusers")
	@WebMethod(action = "addbackofusers")
	@ResponseWrapper(localName = "addbackofusersResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddbackofusersResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addbackofusers(
			@WebParam(name = "firstname", targetNamespace = "") java.lang.String firstname,
			@WebParam(name = "surname", targetNamespace = "") java.lang.String surname,
			@WebParam(name = "username", targetNamespace = "") java.lang.String username,
			@WebParam(name = "msisdn", targetNamespace = "") java.lang.String msisdn,
			@WebParam(name = "email", targetNamespace = "") java.lang.String email,
			@WebParam(name = "profileid", targetNamespace = "") java.lang.String profileid);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "linkaccountrequest", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Linkaccountrequest")
	@WebMethod(action = "linkaccountrequest")
	@ResponseWrapper(localName = "linkaccountrequestResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.LinkaccountrequestResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Linkaccountresponse linkaccountrequest(
			@WebParam(name = "userresourceid", targetNamespace = "") java.lang.String userresourceid,
			@WebParam(name = "profileid", targetNamespace = "") java.lang.String profileid,
			@WebParam(name = "paraentaccountresourceid", targetNamespace = "") java.lang.String paraentaccountresourceid,
			@WebParam(name = "reason", targetNamespace = "") java.lang.String reason);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "suspendaccountholder", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Suspendaccountholder")
	@WebMethod(action = "suspendaccountholder")
	@ResponseWrapper(localName = "suspendaccountholderResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.SuspendaccountholderResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Suspendaccountholderrequestresponse suspendaccountholder(
			@WebParam(name = "resourceid", targetNamespace = "") java.lang.String resourceid,
			@WebParam(name = "confirmcredential", targetNamespace = "") java.lang.String confirmcredential);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addtransferCounttouserprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddtransferCounttouserprofile")
	@WebMethod(action = "addtransferCounttouserprofile")
	@ResponseWrapper(localName = "addtransferCounttouserprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddtransferCounttouserprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addtransferCounttouserprofile(
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile,
			@WebParam(name = "countername", targetNamespace = "") java.lang.String countername,
			@WebParam(name = "description", targetNamespace = "") java.lang.String description,
			@WebParam(name = "countertype", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Transfercounttype countertype,
			@WebParam(name = "transactiontype", targetNamespace = "") java.util.List<java.lang.String> transactiontype,
			@WebParam(name = "limit", targetNamespace = "") java.lang.String limit,
			@WebParam(name = "autoresetcounter", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Autoresetcounterevery autoresetcounter,
			@WebParam(name = "limitmessage", targetNamespace = "") java.lang.String limitmessage,
			@WebParam(name = "extensionparameters", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.ParameterExtension extensionparameters);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addloginCounttouserprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddloginCounttouserprofile")
	@WebMethod(action = "addloginCountuserprofile")
	@ResponseWrapper(localName = "addloginCounttouserprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddloginCounttouserprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addloginCounttouserprofile(
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile,
			@WebParam(name = "countername", targetNamespace = "") java.lang.String countername,
			@WebParam(name = "description", targetNamespace = "") java.lang.String description,
			@WebParam(name = "limit", targetNamespace = "") java.lang.String limit,
			@WebParam(name = "autoresetcounter", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Autoresetcounterevery autoresetcounter,
			@WebParam(name = "limitmessage", targetNamespace = "") java.lang.String limitmessage,
			@WebParam(name = "extensionparameters", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.ParameterExtension extensionparameters);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addthresholdtoaccountprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addthresholdtoaccountprofile")
	@WebMethod(action = "addthresholdtoaccountprofile")
	@ResponseWrapper(localName = "addthresholdtoaccountprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddthresholdtoaccountprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addthresholdtoaccountprofile(
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile,
			@WebParam(name = "countername", targetNamespace = "") java.lang.String countername,
			@WebParam(name = "description", targetNamespace = "") java.lang.String description,
			@WebParam(name = "thresholdtype", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Thresholdtype thresholdtype,
			@WebParam(name = "transactiontype", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Transactiontype transactiontype,
			@WebParam(name = "value", targetNamespace = "") java.lang.String value,
			@WebParam(name = "thresholdmessage", targetNamespace = "") java.lang.String thresholdmessage,
			@WebParam(name = "extensionparameters", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.ParameterExtension extensionparameters);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "isProfileauthorised", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.IsProfileauthorised")
	@WebMethod(action = "isProfileauthorised")
	@ResponseWrapper(localName = "isProfileauthorisedResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.IsProfileauthorisedResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Isprofileathresponse isProfileauthorised(
			@WebParam(name = "profilename", targetNamespace = "") java.lang.String profilename,
			@WebParam(name = "operation", targetNamespace = "") java.lang.String operation,
			@WebParam(name = "permission", targetNamespace = "") java.lang.String permission);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "specifybalancingtypetoaccountprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Specifybalancingtypetoaccountprofile")
	@WebMethod(action = "specifybalancingtypetoaccountprofile")
	@ResponseWrapper(localName = "specifybalancingtypetoaccountprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.SpecifybalancingtypetoaccountprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse specifybalancingtypetoaccountprofile(
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile,
			@WebParam(name = "countername", targetNamespace = "") java.lang.String countername,
			@WebParam(name = "description", targetNamespace = "") java.lang.String description,
			@WebParam(name = "limit", targetNamespace = "") java.lang.String limit,
			@WebParam(name = "autoresetcounter", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Autoresetcounterevery autoresetcounter,
			@WebParam(name = "limitmessage", targetNamespace = "") java.lang.String limitmessage,
			@WebParam(name = "extensionparameters", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.ParameterExtension extensionparameters);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addtransferCountmessagetouserprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddtransferCountmessagetouserprofile")
	@WebMethod(action = "addtransferCountmessagetouserprofile")
	@ResponseWrapper(localName = "addtransferCountmessagetouserprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddtransferCountmessagetouserprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addtransferCountmessagetouserprofile(
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile,
			@WebParam(name = "countername", targetNamespace = "") java.lang.String countername,
			@WebParam(name = "description", targetNamespace = "") java.lang.String description,
			@WebParam(name = "countertype", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Transfercounttype countertype,
			@WebParam(name = "transactiontype", targetNamespace = "") java.lang.String transactiontype,
			@WebParam(name = "autoresetcounter", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Autoresetcounterevery autoresetcounter,
			@WebParam(name = "extensionparameters", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.ParameterExtension extensionparameters);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "approveresetpassword", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Approveresetpassword")
	@WebMethod(action = "approveresetpassword")
	@ResponseWrapper(localName = "approveresetpasswordResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.ApproveresetpasswordResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse approveresetpassword(
			@WebParam(name = "newpassword", targetNamespace = "") java.lang.String newpassword,
			@WebParam(name = "confirmpassword", targetNamespace = "") java.lang.String confirmpassword,
			@WebParam(name = "otp", targetNamespace = "") java.lang.String otp);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addtransferCounttoaccountprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddtransferCounttoaccountprofile")
	@WebMethod(action = "addtransferCounttoaccountprofile")
	@ResponseWrapper(localName = "addtransferCounttoaccountprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddtransferCounttoaccountprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addtransferCounttoaccountprofile(
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile,
			@WebParam(name = "countername", targetNamespace = "") java.lang.String countername,
			@WebParam(name = "description", targetNamespace = "") java.lang.String description,
			@WebParam(name = "countertype", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Transfercounttype countertype,
			@WebParam(name = "transactiontype", targetNamespace = "") java.lang.String transactiontype,
			@WebParam(name = "limit", targetNamespace = "") java.lang.String limit,
			@WebParam(name = "autoresetcounter", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Autoresetcounterevery autoresetcounter,
			@WebParam(name = "limitmessage", targetNamespace = "") java.lang.String limitmessage,
			@WebParam(name = "extensionparameters", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.ParameterExtension extensionparameters);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "registration", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Registration")
	@WebMethod(action = "registration")
	@ResponseWrapper(localName = "registrationResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.RegistrationResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Registrationrequestresponse registration(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username,
			@WebParam(name = "msisdn", targetNamespace = "") java.lang.String msisdn,
			@WebParam(name = "email", targetNamespace = "") java.lang.String email,
			@WebParam(name = "profileid", targetNamespace = "") int profileid,
			@WebParam(name = "bankcodeid", targetNamespace = "") int bankcodeid,
			@WebParam(name = "bankaccount", targetNamespace = "") java.lang.String bankaccount,
			@WebParam(name = "clearingnumber", targetNamespace = "") java.lang.String clearingnumber,
			@WebParam(name = "accountholderdetails", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Accountholderdetails accountholderdetails,
			@WebParam(name = "currencyid", targetNamespace = "") java.lang.String currencyid,
			@WebParam(name = "bankdomainnameid", targetNamespace = "") java.lang.String bankdomainnameid,
			@WebParam(name = "termscondition", targetNamespace = "") java.lang.String termscondition,
			@WebParam(name = "securityquestions", targetNamespace = "") java.util.List<com.swifta.sub.mats.operation.provisioning.v1.Securityquestions> securityquestions);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addthreadholdmessagetouserprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addthreadholdmessagetouserprofile")
	@WebMethod(action = "addthreadholdmessagetouserprofile")
	@ResponseWrapper(localName = "addthreadholdmessagetouserprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddthreadholdmessagetouserprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addthreadholdmessagetouserprofile(
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile,
			@WebParam(name = "countername", targetNamespace = "") java.lang.String countername,
			@WebParam(name = "description", targetNamespace = "") java.lang.String description,
			@WebParam(name = "thresholdtype", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Thresholdtype thresholdtype,
			@WebParam(name = "thresholdmessage", targetNamespace = "") java.lang.String thresholdmessage,
			@WebParam(name = "extensionparameters", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.ParameterExtension extensionparameters);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getProfileofUser", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.GetProfileofUser")
	@WebMethod(action = "getProfileofUser")
	@ResponseWrapper(localName = "getProfileofUserResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.GetProfileofUserResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Getuserprofileresponse getProfileofUser(
			@WebParam(name = "resourceid", targetNamespace = "") java.lang.String resourceid);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addcustodyaccount", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addcustodyaccount")
	@WebMethod(action = "addcustodyaccount")
	@ResponseWrapper(localName = "addcustodyaccountResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddcustodyaccountResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Addcustodyaccountrequestresponse addcustodyaccount(
			@WebParam(name = "currencycode", targetNamespace = "") java.lang.String currencycode,
			@WebParam(name = "bankcode", targetNamespace = "") java.lang.String bankcode,
			@WebParam(name = "accountnumber", targetNamespace = "") java.lang.String accountnumber,
			@WebParam(name = "accountname", targetNamespace = "") java.lang.String accountname,
			@WebParam(name = "bankdomain", targetNamespace = "") java.lang.String bankdomain);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "setparentaccount", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Setparentaccount")
	@WebMethod(action = "setparentaccount")
	@ResponseWrapper(localName = "setparentaccountResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.SetparentaccountResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Setparentrequestresponse setparentaccount(
			@WebParam(name = "userresourceid", targetNamespace = "") java.lang.String userresourceid,
			@WebParam(name = "paraentaccountresourceid", targetNamespace = "") java.lang.String paraentaccountresourceid,
			@WebParam(name = "reason", targetNamespace = "") java.lang.String reason);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "editbackofusers", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Editbackofusers")
	@WebMethod(action = "editbackofusers")
	@ResponseWrapper(localName = "editbackofusersResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.EditbackofusersResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse editbackofusers(
			@WebParam(name = "firstname", targetNamespace = "") java.lang.String firstname,
			@WebParam(name = "surname", targetNamespace = "") java.lang.String surname,
			@WebParam(name = "username", targetNamespace = "") java.lang.String username,
			@WebParam(name = "msisdn", targetNamespace = "") java.lang.String msisdn,
			@WebParam(name = "email", targetNamespace = "") java.lang.String email,
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addthresholdtouserprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addthresholdtouserprofile")
	@WebMethod(action = "addthresholdtouserprofile")
	@ResponseWrapper(localName = "addthresholdtouserprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddthresholdtouserprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addthresholdtouserprofile(
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile,
			@WebParam(name = "thresholdname", targetNamespace = "") java.lang.String thresholdname,
			@WebParam(name = "description", targetNamespace = "") java.lang.String description,
			@WebParam(name = "thresholdtype", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Thresholdtype thresholdtype,
			@WebParam(name = "transactiontype", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Transactiontype transactiontype,
			@WebParam(name = "value", targetNamespace = "") java.lang.String value,
			@WebParam(name = "thresholdmessage", targetNamespace = "") java.lang.String thresholdmessage,
			@WebParam(name = "extensionparameters", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.ParameterExtension extensionparameters);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "viewbackofusers", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Viewbackofusers")
	@WebMethod(action = "viewbackofusers")
	@ResponseWrapper(localName = "viewbackofusersResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.ViewbackofusersResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse viewbackofusers(
			@WebParam(name = "filter", targetNamespace = "") java.lang.String filter);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "deletebackofusers", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Deletebackofusers")
	@WebMethod(action = "deletebackofusers")
	@ResponseWrapper(localName = "deletebackofusersResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.DeletebackofusersResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse deletebackofusers(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username,
			@WebParam(name = "msisdn", targetNamespace = "") java.lang.String msisdn,
			@WebParam(name = "email", targetNamespace = "") java.lang.String email);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addservicetouserprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addservicetouserprofile")
	@WebMethod(action = "addservicetouserprofile")
	@ResponseWrapper(localName = "addservicetouserprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddservicetouserprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addservicetouserprofile(
			@WebParam(name = "servicetype", targetNamespace = "") java.lang.String servicetype,
			@WebParam(name = "extensionparameters", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.ParameterExtension extensionparameters);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addpermissionstouserprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addpermissionstouserprofile")
	@WebMethod(action = "addpermissionstouserprofile")
	@ResponseWrapper(localName = "addpermissionstouserprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddpermissionstouserprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addpermissionstouserprofile(
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile,
			@WebParam(name = "activepermissions", targetNamespace = "") java.util.List<java.lang.String> activepermissions);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "setdefaultaccount", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Setdefaultaccount")
	@WebMethod(action = "setdefaultaccount")
	@ResponseWrapper(localName = "setdefaultaccountResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.SetdefaultaccountResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.SetDefaultaccountrequestresponse setdefaultaccount(
			@WebParam(name = "userresourceid", targetNamespace = "") java.lang.String userresourceid,
			@WebParam(name = "paraentaccountresourceid", targetNamespace = "") java.lang.String paraentaccountresourceid,
			@WebParam(name = "reason", targetNamespace = "") java.lang.String reason);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "activationrequest", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Activationrequest")
	@WebMethod(action = "activation")
	@ResponseWrapper(localName = "activationrequestResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.ActivationrequestResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Activationrequestresponse activationrequest(
			@WebParam(name = "resourceid", targetNamespace = "") java.lang.String resourceid,
			@WebParam(name = "credential", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Credentials credential,
			@WebParam(name = "securityquestionanswer", targetNamespace = "") java.lang.String securityquestionanswer,
			@WebParam(name = "identificationno", targetNamespace = "") java.lang.String identificationno,
			@WebParam(name = "bankdomainid", targetNamespace = "") java.lang.String bankdomainid,
			@WebParam(name = "currency", targetNamespace = "") java.lang.String currency);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "disconnectaccount", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Disconnectaccount")
	@WebMethod(action = "disconnectaccount")
	@ResponseWrapper(localName = "disconnectaccountResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.DisconnectaccountResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Disconnectaccountrequestresponse disconnectaccount(
			@WebParam(name = "userresourceid", targetNamespace = "") java.lang.String userresourceid,
			@WebParam(name = "paraentaccountresourceid", targetNamespace = "") java.lang.String paraentaccountresourceid,
			@WebParam(name = "reason", targetNamespace = "") java.lang.String reason);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "authenticate", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Authenticate")
	@WebMethod(action = "authenticate")
	@ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AuthenticateResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Authenticationresponse authenticate(
			@WebParam(name = "resourceid", targetNamespace = "") java.lang.String resourceid,
			@WebParam(name = "password", targetNamespace = "") java.lang.String password);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addaccount", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addaccount")
	@WebMethod(action = "addaccount")
	@ResponseWrapper(localName = "addaccountResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddaccountResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Addaccountrequestresponse addaccount(
			@WebParam(name = "accounttype", targetNamespace = "") java.lang.String accounttype,
			@WebParam(name = "accountprofileid", targetNamespace = "") java.lang.String accountprofileid,
			@WebParam(name = "accountreferenceprofile", targetNamespace = "") java.lang.String accountreferenceprofile);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addthreadholdmessagetoaccountprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addthreadholdmessagetoaccountprofile")
	@WebMethod(action = "addthreadholdmessagetoaccountprofile")
	@ResponseWrapper(localName = "addthreadholdmessagetoaccountprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddthreadholdmessagetoaccountprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addthreadholdmessagetoaccountprofile(
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile,
			@WebParam(name = "countername", targetNamespace = "") java.lang.String countername,
			@WebParam(name = "description", targetNamespace = "") java.lang.String description,
			@WebParam(name = "thresholdtype", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Thresholdtype thresholdtype,
			@WebParam(name = "thresholdmessage", targetNamespace = "") java.lang.String thresholdmessage,
			@WebParam(name = "extensionparameters", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.ParameterExtension extensionparameters);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addaccounttoexistinguser", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addaccounttoexistinguser")
	@WebMethod(action = "addaccounttoexistinguser")
	@ResponseWrapper(localName = "addaccounttoexistinguserResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddaccounttoexistinguserResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Addaccounttoexistinguserrequestresponse addaccounttoexistinguser(
			@WebParam(name = "resourceid", targetNamespace = "") java.lang.String resourceid,
			@WebParam(name = "accounttype", targetNamespace = "") java.lang.String accounttype,
			@WebParam(name = "profileid", targetNamespace = "") java.lang.String profileid,
			@WebParam(name = "currency", targetNamespace = "") java.lang.String currency);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addtransferCountmessagetoaccountprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddtransferCountmessagetoaccountprofile")
	@WebMethod(action = "addtransferCountmessagetoaccountprofile")
	@ResponseWrapper(localName = "addtransferCountmessagetoaccountprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddtransferCountmessagetoaccountprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addtransferCountmessagetoaccountprofile(
			@WebParam(name = "profile", targetNamespace = "") java.lang.String profile,
			@WebParam(name = "countername", targetNamespace = "") java.lang.String countername,
			@WebParam(name = "description", targetNamespace = "") java.lang.String description,
			@WebParam(name = "countertype", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Transfercounttype countertype,
			@WebParam(name = "transactiontype", targetNamespace = "") java.lang.String transactiontype,
			@WebParam(name = "autoresetcounter", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Autoresetcounterevery autoresetcounter,
			@WebParam(name = "extensionparameters", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.ParameterExtension extensionparameters);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "changepassword", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Changepassword")
	@WebMethod(action = "changepassword")
	@ResponseWrapper(localName = "changepasswordResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.ChangepasswordResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse changepassword(
			@WebParam(name = "currentpassword", targetNamespace = "") java.lang.String currentpassword,
			@WebParam(name = "newpassword", targetNamespace = "") java.lang.String newpassword,
			@WebParam(name = "confirmpassword", targetNamespace = "") java.lang.String confirmpassword);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addglobalsetting", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addglobalsetting")
	@WebMethod(action = "addglobalsetting")
	@ResponseWrapper(localName = "addglobalsettingResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddglobalsettingResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addglobalsetting(
			@WebParam(name = "defaultuserprofile", targetNamespace = "") java.lang.String defaultuserprofile,
			@WebParam(name = "defaultuseraccountprofile", targetNamespace = "") java.lang.String defaultuseraccountprofile);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "setprofilerequest", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Setprofilerequest")
	@WebMethod(action = "setprofilerequest")
	@ResponseWrapper(localName = "setprofilerequestResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.SetprofilerequestResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse setprofilerequest(
			@WebParam(name = "resourceid", targetNamespace = "") java.lang.String resourceid,
			@WebParam(name = "profileid", targetNamespace = "") java.lang.String profileid,
			@WebParam(name = "reason", targetNamespace = "") java.lang.String reason);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "addprofile", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.Addprofile")
	@WebMethod(action = "addprofile")
	@ResponseWrapper(localName = "addprofileResponse", targetNamespace = "http://swifta.com/sub/mats/operation/provisioning/v1.0", className = "com.swifta.sub.mats.operation.provisioning.v1.AddprofileResponse")
	public com.swifta.sub.mats.operation.provisioning.v1.Operationresponse addprofile(
			@WebParam(name = "profilename", targetNamespace = "") java.lang.String profilename,
			@WebParam(name = "profiletype", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.Profiletype profiletype,
			@WebParam(name = "extensionparameters", targetNamespace = "") com.swifta.sub.mats.operation.provisioning.v1.ParameterExtension extensionparameters);
}
